version: "3.9"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.1
    environment:
    ELASTICSEARCH_HOSTS: http://node01:9200
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - node01
  database:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: "root"
    MYSQL_USER: "root"
    MYSQL_PASS: "root"
  ports:
    - 13306:3306
  nginx:
    depends_on:
    image: nginx:alpine
    restart: always
