version: "3.9"
services:
  kibana:
    image: kibana:7.13.2
    ports:
      - 5601:5601
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_PASS: "root"
    ports:
      - 13306:3306
  nginx:
    image: nginx
    restart: always
